import { expect, test } from '@playwright/test'

test('로그인 후 시드 카탈로그 카드·검색·Lv1 필터', async ({ page }) => {
  const loginId = `e2e-catalog-${Date.now()}`
  await page.goto('/signup')
  await page.getByLabel('ID').fill(loginId)
  await page.getByLabel('비밀번호', { exact: true }).fill('e2e-password-1234')
  await page.getByLabel('이름').fill('가상 사용자')
  await page.getByLabel('비밀번호 확인').fill('e2e-password-1234')
  await page.getByRole('button', { name: '회원가입' }).click()

  await expect(page.getByRole('link', { name: /새 대화/ })).toHaveCount(12)
  await page.getByPlaceholder('이름 · 요약 · 업무 분류 검색').fill('프로토콜')
  await expect(page.getByRole('link', { name: /새 대화/ })).toHaveCount(1)
  await page.getByPlaceholder('이름 · 요약 · 업무 분류 검색').fill('')
  await page.getByRole('button', { name: 'Record', exact: true }).click()
  const assistants = await (await page.request.get('/api/assistants')).json() as Array<{ status: string; classifications: Array<{ level1: string; level2: string; level1CodeId: string; level2CodeId: string }> }>
  const recordCount = assistants.filter(a => a.status !== 'retired' && a.classifications.some(path => path.level1 === 'Record')).length
  await expect(page.getByRole('link', { name: /새 대화/ })).toHaveCount(recordCount)
  await expect(page).toHaveURL(/l1=/)
  const selectedUrl = page.url()
  await page.getByRole('tab', { name: '전체 대화 칸반' }).click()
  await expect(page).toHaveURL(/view=kanban/)
  await page.getByRole('tab', { name: '에이전트 카드' }).click()
  expect(new URL(page.url()).searchParams.getAll('l1')).toEqual(new URL(selectedUrl).searchParams.getAll('l1'))
  await page.getByRole('button', { name: 'SDLC', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Record', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByRole('button', { name: 'SDLC', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.goBack()
  await expect(page.getByRole('button', { name: 'SDLC', exact: true })).toHaveAttribute('aria-pressed', 'false')
  await page.goForward()
  await expect(page.getByRole('button', { name: 'SDLC', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await page.getByPlaceholder('이름 · 요약 · 업무 분류 검색').fill('존재하지 않는 에이전트')
  await expect(page.getByRole('button', { name: '검색어 지우기' })).toBeVisible()
  await expect(page.getByRole('button', { name: '필터 2개 초기화' })).toBeVisible()
  await page.getByRole('button', { name: '검색어 지우기' }).click()
  await page.getByRole('button', { name: '초기화', exact: true }).click()
  await expect(page.getByRole('link', { name: /새 대화/ })).toHaveCount(12)
  await expect(page.getByRole('link', { name: /편집$/ })).toHaveCount(0)
})
